---
title: "Untitled"
format: html
editor: visual
---

## Quarto


When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
df <- mtcars
df$cyl <- as.factor(df$cyl)

get_box_stats <- function(y, upper_limit = max(t$UniquePeptides) * 1.15) {
  return(data.frame(
    y = 0.95 * upper_limit,
    label = paste("CV =", round(CV(y)*100, 2), "%")
  ))
}
```

```{r}
ggplot(df, aes(y = cyl, x = mpg, fill = cyl)) +
  geom_boxplot() +
  scale_fill_manual(values = c("#0099f8", "#e74c3c", "#2ecc71")) +
  stat_summary(fun.data = get_box_stats, geom = "text", vjust = 0.5, hjust = 0.9, size=2.5) +
  theme_classic()
```

```{r}
t %>% 
  ggplot(aes(UniquePeptides, R.Condition, fill=R.Condition))+
  geom_boxplot()+
  stat_summary(fun.data = get_box_stats, geom = "text", vjust = 0.5, hjust = 0.9, size=3.5)+
  theme(legend.position = "none")+
  labs(title="", subtitle="", x="", y="")+
  theme_minimal()
```

```{r}
MDBL_MakeLabel <- function(data){
  for (n in seq(1,200, by=1)){
  data %>% 
  distinct(R.FileName) %>% 
  mutate(stringStart = str_sub(R.FileName, 1, n)) %>% 
  distinct(stringStart) %>% nrow() -> t
  if(t>1)
    {
    print(paste0("Common start = ", dfBGS %>% head(1) %>% mutate(stringStart = str_sub(R.FileName, 1, n-1)) %>%  pull(stringStart)))  
    break
    }
}

data %>% 
  distinct(R.FileName) %>%
  mutate(Part = str_sub(R.FileName, start = 1, end=n )) %>% 
  rowwise() %>% 
  mutate(n = stringi::stri_locate_last(Part, fixed='_')[1],
         Label = str_sub(R.FileName, start = n+1, end = 300)) %>% 
  select(R.FileName, Label) -> d
return(d)
}

dfBGS %>% 
  MDBL_MakeLabel()

```

%>% 
